---
# Tasks to install and configuure redis for Wordpress

- name: Install redis
  yum:
    name: redis
    state: latest

# TODO: Custom Redis config
#- name: Copy redis.conf for Redis
#  template:
#    dest: /etc/
#    src: redis.conf

- name: enable redis service on reboot
  service:
    name: redis
    enabled: yes
    state: restarted
  ignore_errors: yes

# NOTE: keep as reference, but this is not necessary at this scale
# - name: optimize system
#   include_tasks: optimize.yml
#   when: rd_optimize == true
