---
# Tasks to install and configuure redis for Wordpress
# OLD Source: https://www.digitalocean.com/community/tutorials/how-to-configure-redis-caching-to-speed-up-wordpress-on-ubuntu-14-04
# NEW Source: https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/
# and https://easyengine.io/tutorials/php/redis-php-sessions/
# NOTE: implementation is also in php-fpm role
# TODO:
# 1.) NEEDS TESTING - This but for CentOS: https://easyengine.io/tutorials/php/redis-php-sessions/

- name: Install redis
  yum:
    name: redis
    state: latest

# Still necessary???
#- name: Copy redis.conf for Redis
#  template:
#    src: redis.conf
#    dest: /etc/

- name: enable redis service on reboot
  service:
    name: redis
    enabled: yes
    state: restarted
  ignore_errors: yes

- name: optimize system
  include_tasks: optimize.yml
  when: rd_optimize == true
