---
# Tasks to install and configuure redis for Wordpress
# OLD Source: https://www.digitalocean.com/community/tutorials/how-to-configure-redis-caching-to-speed-up-wordpress-on-ubuntu-14-04
# NEW Source: https://www.justinsilver.com/technology/linux/lemp-centos-7-nginx-php7-redis-wordpress/
# NEW Source2: https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/
# and https://easyengine.io/tutorials/php/redis-php-sessions/
# TODO:
# 1.) NEEDS TESTING - This but for CentOS: https://easyengine.io/tutorials/php/redis-php-sessions/

- name: Install redis
  yum:
    name: redis
    state: latest

# Still necessary???
#- name: Copy redis.conf for Redis
#  template:
#    src: redis.conf
#    dest: /etc/

- name: fix redis background saves on low memory
  block:
    - name: sysctl vm.overcommit_memory=1
      command: sysctl vm.overcommit_memory=1

    - name: create 88-vm.overcommit_memory.conf and set vm.overcommit_memory = 1
      lineinfile:
        path: /etc/sysctl.d/88-vm.overcommit_memory.conf
        regexp: '^vm.overcommit_memory ='
        line: 'vm.overcommit_memory = 1'
        create: yes

- name: increase max connections
  block:
    - name: sysctl -w net.core.somaxconn=65535
      command: sysctl -w net.core.somaxconn=65535

    - name: create 88-net.core.somaxconn.conf and set net.core.somaxconn = 65535
      lineinfile:
        path: /etc/sysctl.d/88-net.core.somaxconn.conf
        regexp: '^net.core.somaxconn ='
        line: 'net.core.somaxconn = 65535'
        create: yes

    - name: sysctl -w fs.file-max=100000
      command: sysctl -w fs.file-max=100000

    - name: create 88-fs.file-max.conf and set fs.file-max = 100000
      lineinfile:
        path: /etc/sysctl.d/88-fs.file-max.conf
        regexp: '^fs.file-max ='
        line: 'fs.file-max = 100000'
        create: yes

    - name: set tcp-backlog 65535
      command: sed -i "s|^tcp-backlog [[:digit:]]\+|tcp-backlog 65535|" /etc/redis.conf

- name: enable redis service on reboot
  service:
    name: redis
    enabled: yes
    state: restarted
  ignore_errors: yes

#- name: start or restart redis
#  shell: (service redis status > /dev/null && service redis restart) || service redis start

# Why disable hugepage tables: https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

- name: Copy disable-transparent-hugepages
  copy:
    src: disable-transparent-hugepages
    dest: /etc/init.d/disable-transparent-hugepages

- name: Set permissions for disable-transparent-hugepages
  file:
    path: /etc/init.d/disable-transparent-hugepages
    mode: 755

- name: execute disable-transparent-hugepages
  shell: chkconfig --add disable-transparent-hugepages
  args:
    chdir: /etc/init.d/
    #creates: ??? or

- name: Configure Tuned, CentOS 7
  block:
    - name: create /etc/tuned/no-thp
      file:
        path: /etc/tuned/no-thp
        state: directory

    - name: copy tuned.conf
      copy:
        src: tuned.conf
        dest: /etc/tuned/no-thp/tuned.conf

    - name: set tuned-adm profile to no-thp
    - command: tuned-adm profile no-thp
      args:
        chdir: /etc/tuned/no-thp/
        #creates: ???
